#!/bin/bash

INTERFACE=$1
STATUS=$2

fallback_ssid="GNSS"
fallback_password="12345678"

check_wifi() {
    # Comprueba si hay una conexión activa en la interfaz wlan0
    nmcli -t -f DEVICE,STATE device | grep wlan0 | grep -q "connected"
}

create_fallback() {
    # Verifica si el AP ya está configurado
    if ! nmcli con show | grep -q "$fallback_ssid"; then
        nmcli con add type wifi ifname wlan0 con-name $fallback_ssid autoconnect yes ssid $fallback_ssid
        nmcli con modify $fallback_ssid 802-11-wireless.mode ap 802-11-wireless.band bg ipv4.method shared
        nmcli con modify $fallback_ssid 802-11-wireless-security.key-mgmt wpa-psk 802-11-wireless-security.psk $fallback_password
    fi
}

activate_fallback() {
    create_fallback
    nmcli con up $fallback_ssid
}

connect_to_known_network() {
    # Intenta conectarse a una red conocida
    for conn in $(nmcli -t -f NAME,UUID con show | grep -vE "GNSS|lo" | cut -d':' -f1)
    do
        # Intentar conectarse
        nmcli con up id "$conn"
        sleep 10
        # Verificar si se conectó exitosamente
        if check_wifi; then
            return 0
        fi
    done
    return 1
}

# Crear fallback si no existe
create_fallback

# Si la interfaz es wlan0 y el estado es "up"
if [ "$INTERFACE" == "wlan0" ] && [ "$STATUS" == "up" ]; then
    # Si no hay conexión activa y no puede conectarse a una red conocida
    if ! check_wifi && ! connect_to_known_network; then
        # Activa el fallback mode
        activate_fallback
    fi
fi

